<template>
	<div>
		<div class="coin-details-hero-bg position-relative coin-details-hero-border custom-container">
			<FrontendBreadcrumb />
			<div class="coin-hero-area ptb50 position">
				<div class="frequently-circle"></div>
				<div class="container">
					<div class="row align-items-center">
						<div class="col-lg-7">
							<div class="learn-earn-hero-left">
								<div class="hero-area-text">
									<h3>Privacy Policy</h3>
									<p class="mb-0">A Privacy Policy explains how your personal information is collected, used, and protected. It ensures transparency, outlining your rights, data-sharing practices, and the security measures taken to safeguard your data.</p>
								</div>
							</div>
						</div>
						<div class="col-lg-5">
							<div class="box-bg h-100">
								<div class="token-card-thumnails position-relative m-0 h-100">
									<nuxt-img src="/images/thumbnail/privacy.png" alt="img" class="w-100 h-100 object-fit-cover" />
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<section class="privacy-policy-section mt80 position-relative">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<!-- card  item-->
						<div class="token-card-main-area learn-description-box mt80">
							<div class="section-heading">
								<h3 class="text-shadow">Overview</h3>
								<p>MyCoinpoll (referred to as "we" or "us") is committed to safeguarding the privacy and security of your personal information. This Privacy Policy outlines how we collect, use, and protect your data when you visit our website and use our services. By accessing or using MyCoinpoll, you consent to the terms outlined in this Privacy Policy.</p>
							</div>
						</div>

						<div class="token-card-main-area learn-description-box mt80">
							<div class="section-heading">
								<h3 class="text-shadow">II. Collection of Personal Information</h3>
								<ul>
									<li>
										<p>
											<b>Information Provided by You:</b>
											<br />
											We collect personal data, such as name, email address, and phone number, only when necessary and with your consent. This information is used for loan mediation purposes and to enhance our services. We do not disclose this data without your permission.
										</p>
									</li>
									<li>
										<p>
											<b>Cookies:</b>
											<br />
											MyCoinpoll utilizes cookies to improve your browsing experience. These text files help store login data and track your visits to our platform. You can turn off cookies in your browser settings, although it may impact certain functionalities.
										</p>
									</li>
									<li>
										<p>
											<b>Contact and Correspondence:</b>
											<br />
											When you contact us via email, we securely store the provided information to process your inquiries and subsequent correspondence.
										</p>
									</li>
									<li>
										<p>
											<b>Comments and Contributions:</b>
											<br />
											User comments on our blog and loan listings may require storing IP addresses to prevent illegal content. This is done to ensure the safety and integrity of our platform.
										</p>
									</li>
									<li>
										<p>
											<b>Blog Subscriptions:</b>
											<br />
											If you subscribe to comments on our blog, we collect your email address for communication purposes. Your subscription data, including your IP address and date, is stored to prevent misuse and can be revoked anytime.
										</p>
									</li>
								</ul>
							</div>
						</div>

						<div class="token-card-main-area learn-description-box mt80">
							<div class="section-heading">
								<h3 class="text-shadow">III. Website Interaction and Data Collection</h3>
								<ul>
									<li>
										<p>
											<b>Access Data/Server Log Files:</b>
											<br />
											Server log files capture your visit information, including IP address, requested files, date and time, data transmitted, browser type, referrer URL, and more. This data is used for statistical analysis and aids in resolving any illegal use of our services.
										</p>
									</li>
									<li>
										<p>
											<b>Google Analytics:</b>
											<br />
											MyCoinpoll employs Google Analytics to analyze website usage. Information generated by cookies, including IP addresses, is transmitted and stored by Google servers. Google Analytics helps us enhance user experience and improve our services.
										</p>
									</li>
									<li>
										<p>
											<b>Liability for Links:</b>
											<br />
											Our website may contain links to external providers. While we checked these links at the time of placement, the content behind them was not integrated into our offer. Any changes in linked content are addressed promptly upon identification.
										</p>
									</li>
								</ul>
							</div>
						</div>

						<div class="token-card-main-area learn-description-box mt80">
							<div class="section-heading">
								<h3 class="text-shadow">IV. Right to Information</h3>
								<ul>
									<li>
										<p>You have the right to request information about the personal data we hold about you, free of charge, to a reasonable extent.</p>
									</li>
								</ul>
							</div>
						</div>

						<div class="token-card-main-area learn-description-box mt80">
							<div class="section-heading">
								<h3 class="text-shadow">V. Changes, Corrections, Updates, and Revocation</h3>
								<ul>
									<li>
										<p>
											<b>Review and Update:</b>
											<br />
											You have the right to review and update your data. If assistance is needed, our support team is ready to help.
										</p>
									</li>
									<li>
										<p>
											<b>Lock and Delete:</b>
											<br />
											You can request the locking or deletion of your data if it is not subject to statutory retention obligations. Data is also deleted if you revoke your permission or if storage is no longer legally possible.
										</p>
									</li>
									<li>
										<p>
											<b>Revocation:</b>
											<br />
											You can withdraw your consent for future data collection, processing, and utilization by emailing us.
										</p>
									</li>
								</ul>
							</div>
						</div>

						<div class="token-card-main-area learn-description-box mt80">
							<div class="section-heading">
								<h3 class="text-shadow">VI. Security Measures</h3>
								<ul>
									<li>
										<p>MyCoinpoll employs industry-standard security measures to protect your personal information from unauthorized access, disclosure, alteration, and destruction. We regularly review and update our security protocols to ensure the ongoing integrity of your data.</p>
									</li>
								</ul>
							</div>
						</div>

						<div class="token-card-main-area learn-description-box mt80">
							<div class="section-heading">
								<h3 class="text-shadow">VII. Updates to Privacy Policy</h3>
								<ul>
									<li>
										<p>We may update this Privacy Policy to reflect changes in our practices or legal requirements. It is recommended to review this policy periodically for any updates. By continuing to use MyCoinpoll after modifications, you acknowledge and agree to the revised terms.</p>
									</li>
								</ul>
							</div>
						</div>

						<div class="token-card-main-area learn-description-box mt80">
							<div class="section-heading">
								<h3 class="text-shadow">VIII. Contact Information</h3>
								<ul>
									<li>
										<p>For any inquiries, concerns, or requests related to your privacy, please get in touch with us at support@mycoinpoll.com.</p>
									</li>
									<li>
										<p>By using MyCoinpoll, you acknowledge and agree to the terms outlined in this Privacy Policy. Last updated: 6th-January-2024.</p>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="learn-circle1 circle-effect1"></div>
			<div class="learn-circle2 circle-effect2"></div>
			<div class="learn-circle3 circle-effect2"></div>
			<div class="learn-circle4 circle-effect5"></div>
			<div class="line-shap-animation learn-circle5"></div>
		</section>
	</div>
</template>

<script lang="ts" setup>
</script>

<style>
</style>