
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'EcmPurchaseIcoInfo': typeof import("../components/EcmPurchase/IcoInfo.vue")['default']
    'EcmPurchaseIcoStat': typeof import("../components/EcmPurchase/IcoStat.vue")['default']
    'EcmPurchase': typeof import("../components/EcmPurchase/Index.vue")['default']
    'EcmPurchaseReferral': typeof import("../components/EcmPurchase/Referral.vue")['default']
    'FormGroupButton': typeof import("../components/FormGroup/Button.vue")['default']
    'FormGroupCheckbox': typeof import("../components/FormGroup/Checkbox.vue")['default']
    'FormGroupEditor': typeof import("../components/FormGroup/Editor.vue")['default']
    'FormGroupHasError': typeof import("../components/FormGroup/HasError.vue")['default']
    'FormGroupInput': typeof import("../components/FormGroup/Input.vue")['default']
    'FormGroupInputGroup': typeof import("../components/FormGroup/InputGroup.vue")['default']
    'FormGroupPhoto': typeof import("../components/FormGroup/Photo.vue")['default']
    'FormGroupSelect': typeof import("../components/FormGroup/Select.vue")['default']
    'FormGroupTag': typeof import("../components/FormGroup/Tag.vue")['default']
    'FormGroupTextarea': typeof import("../components/FormGroup/Textarea.vue")['default']
    'FormGroupToggle': typeof import("../components/FormGroup/Toggle.vue")['default']
    'FrontendBreadcrumb': typeof import("../components/Frontend/Breadcrumb.vue")['default']
    'FrontendFooter': typeof import("../components/Frontend/Footer.vue")['default']
    'FrontendHeader': typeof import("../components/Frontend/Header.vue")['default']
    'FrontendHomeChain': typeof import("../components/Frontend/Home/Chain.vue")['default']
    'FrontendHomeFlipbox': typeof import("../components/Frontend/Home/Flipbox.vue")['default']
    'FrontendHomeHero': typeof import("../components/Frontend/Home/Hero.vue")['default']
    'FrontendHomeRunningToken': typeof import("../components/Frontend/Home/RunningToken.vue")['default']
    'FrontendNewsletter': typeof import("../components/Frontend/Newsletter.vue")['default']
    'SkeletonsTokenCardSkeleton': typeof import("../components/Skeletons/TokenCardSkeleton.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyEcmPurchaseIcoInfo': typeof import("../components/EcmPurchase/IcoInfo.vue")['default']
    'LazyEcmPurchaseIcoStat': typeof import("../components/EcmPurchase/IcoStat.vue")['default']
    'LazyEcmPurchase': typeof import("../components/EcmPurchase/Index.vue")['default']
    'LazyEcmPurchaseReferral': typeof import("../components/EcmPurchase/Referral.vue")['default']
    'LazyFormGroupButton': typeof import("../components/FormGroup/Button.vue")['default']
    'LazyFormGroupCheckbox': typeof import("../components/FormGroup/Checkbox.vue")['default']
    'LazyFormGroupEditor': typeof import("../components/FormGroup/Editor.vue")['default']
    'LazyFormGroupHasError': typeof import("../components/FormGroup/HasError.vue")['default']
    'LazyFormGroupInput': typeof import("../components/FormGroup/Input.vue")['default']
    'LazyFormGroupInputGroup': typeof import("../components/FormGroup/InputGroup.vue")['default']
    'LazyFormGroupPhoto': typeof import("../components/FormGroup/Photo.vue")['default']
    'LazyFormGroupSelect': typeof import("../components/FormGroup/Select.vue")['default']
    'LazyFormGroupTag': typeof import("../components/FormGroup/Tag.vue")['default']
    'LazyFormGroupTextarea': typeof import("../components/FormGroup/Textarea.vue")['default']
    'LazyFormGroupToggle': typeof import("../components/FormGroup/Toggle.vue")['default']
    'LazyFrontendBreadcrumb': typeof import("../components/Frontend/Breadcrumb.vue")['default']
    'LazyFrontendFooter': typeof import("../components/Frontend/Footer.vue")['default']
    'LazyFrontendHeader': typeof import("../components/Frontend/Header.vue")['default']
    'LazyFrontendHomeChain': typeof import("../components/Frontend/Home/Chain.vue")['default']
    'LazyFrontendHomeFlipbox': typeof import("../components/Frontend/Home/Flipbox.vue")['default']
    'LazyFrontendHomeHero': typeof import("../components/Frontend/Home/Hero.vue")['default']
    'LazyFrontendHomeRunningToken': typeof import("../components/Frontend/Home/RunningToken.vue")['default']
    'LazyFrontendNewsletter': typeof import("../components/Frontend/Newsletter.vue")['default']
    'LazySkeletonsTokenCardSkeleton': typeof import("../components/Skeletons/TokenCardSkeleton.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const EcmPurchaseIcoInfo: typeof import("../components/EcmPurchase/IcoInfo.vue")['default']
export const EcmPurchaseIcoStat: typeof import("../components/EcmPurchase/IcoStat.vue")['default']
export const EcmPurchase: typeof import("../components/EcmPurchase/Index.vue")['default']
export const EcmPurchaseReferral: typeof import("../components/EcmPurchase/Referral.vue")['default']
export const FormGroupButton: typeof import("../components/FormGroup/Button.vue")['default']
export const FormGroupCheckbox: typeof import("../components/FormGroup/Checkbox.vue")['default']
export const FormGroupEditor: typeof import("../components/FormGroup/Editor.vue")['default']
export const FormGroupHasError: typeof import("../components/FormGroup/HasError.vue")['default']
export const FormGroupInput: typeof import("../components/FormGroup/Input.vue")['default']
export const FormGroupInputGroup: typeof import("../components/FormGroup/InputGroup.vue")['default']
export const FormGroupPhoto: typeof import("../components/FormGroup/Photo.vue")['default']
export const FormGroupSelect: typeof import("../components/FormGroup/Select.vue")['default']
export const FormGroupTag: typeof import("../components/FormGroup/Tag.vue")['default']
export const FormGroupTextarea: typeof import("../components/FormGroup/Textarea.vue")['default']
export const FormGroupToggle: typeof import("../components/FormGroup/Toggle.vue")['default']
export const FrontendBreadcrumb: typeof import("../components/Frontend/Breadcrumb.vue")['default']
export const FrontendFooter: typeof import("../components/Frontend/Footer.vue")['default']
export const FrontendHeader: typeof import("../components/Frontend/Header.vue")['default']
export const FrontendHomeChain: typeof import("../components/Frontend/Home/Chain.vue")['default']
export const FrontendHomeFlipbox: typeof import("../components/Frontend/Home/Flipbox.vue")['default']
export const FrontendHomeHero: typeof import("../components/Frontend/Home/Hero.vue")['default']
export const FrontendHomeRunningToken: typeof import("../components/Frontend/Home/RunningToken.vue")['default']
export const FrontendNewsletter: typeof import("../components/Frontend/Newsletter.vue")['default']
export const SkeletonsTokenCardSkeleton: typeof import("../components/Skeletons/TokenCardSkeleton.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyEcmPurchaseIcoInfo: typeof import("../components/EcmPurchase/IcoInfo.vue")['default']
export const LazyEcmPurchaseIcoStat: typeof import("../components/EcmPurchase/IcoStat.vue")['default']
export const LazyEcmPurchase: typeof import("../components/EcmPurchase/Index.vue")['default']
export const LazyEcmPurchaseReferral: typeof import("../components/EcmPurchase/Referral.vue")['default']
export const LazyFormGroupButton: typeof import("../components/FormGroup/Button.vue")['default']
export const LazyFormGroupCheckbox: typeof import("../components/FormGroup/Checkbox.vue")['default']
export const LazyFormGroupEditor: typeof import("../components/FormGroup/Editor.vue")['default']
export const LazyFormGroupHasError: typeof import("../components/FormGroup/HasError.vue")['default']
export const LazyFormGroupInput: typeof import("../components/FormGroup/Input.vue")['default']
export const LazyFormGroupInputGroup: typeof import("../components/FormGroup/InputGroup.vue")['default']
export const LazyFormGroupPhoto: typeof import("../components/FormGroup/Photo.vue")['default']
export const LazyFormGroupSelect: typeof import("../components/FormGroup/Select.vue")['default']
export const LazyFormGroupTag: typeof import("../components/FormGroup/Tag.vue")['default']
export const LazyFormGroupTextarea: typeof import("../components/FormGroup/Textarea.vue")['default']
export const LazyFormGroupToggle: typeof import("../components/FormGroup/Toggle.vue")['default']
export const LazyFrontendBreadcrumb: typeof import("../components/Frontend/Breadcrumb.vue")['default']
export const LazyFrontendFooter: typeof import("../components/Frontend/Footer.vue")['default']
export const LazyFrontendHeader: typeof import("../components/Frontend/Header.vue")['default']
export const LazyFrontendHomeChain: typeof import("../components/Frontend/Home/Chain.vue")['default']
export const LazyFrontendHomeFlipbox: typeof import("../components/Frontend/Home/Flipbox.vue")['default']
export const LazyFrontendHomeHero: typeof import("../components/Frontend/Home/Hero.vue")['default']
export const LazyFrontendHomeRunningToken: typeof import("../components/Frontend/Home/RunningToken.vue")['default']
export const LazyFrontendNewsletter: typeof import("../components/Frontend/Newsletter.vue")['default']
export const LazySkeletonsTokenCardSkeleton: typeof import("../components/Skeletons/TokenCardSkeleton.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
